# Generated by Django 3.1.4 on 2020-12-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.PositiveIntegerField()),
                ('institucion', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('direccion', models.TextField()),
                ('celular', models.PositiveIntegerField()),
                ('motivo', models.TextField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
