# Generated by Django 3.1.4 on 2020-12-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='cedula',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='celular',
            field=models.CharField(max_length=10),
        ),
    ]
