# Generated by Django 3.1.4 on 2021-01-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0003_auto_20210114_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='entrada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='salida',
            field=models.TimeField(),
        ),
    ]
