# Generated by Django 3.1.4 on 2021-01-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0005_auto_20210114_0419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institucion',
            new_name='Instituciones',
        ),
    ]
