# Generated by Django 3.1.4 on 2021-01-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0006_auto_20210114_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitante.instituciones'),
        ),
    ]
