# Generated by Django 3.1.4 on 2021-01-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0007_auto_20210114_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='entrada',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='salida',
            field=models.TimeField(blank=True),
        ),
    ]
