# Generated by Django 3.1.4 on 2021-01-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0009_auto_20210114_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituciones',
            name='tipo',
            field=models.CharField(default=['A', 'B', 'C'], max_length=50),
        ),
    ]
