# Generated by Django 3.1.4 on 2021-01-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0011_auto_20210114_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituciones',
            name='tipo',
            field=models.CharField(choices=[('institucion', 'institucion'), ('proveedor', 'proveedor')], max_length=50),
        ),
    ]
