# Generated by Django 3.1.4 on 2021-01-14 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0012_auto_20210114_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
