# Generated by Django 3.1.4 on 2021-01-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0013_auto_20210114_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='entrada',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='salida',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
